#!/bin/bash
set -ex

if [ -z "$@" ]; then
  echo "Expecting one or more arguments"
  exit 1
fi

source scripts/spack_setup.sh fetch

export PATH="$PATH:$(spack location --install-dir $SPACK_SPEC)/bin/"

cd $WORKSPACE

$*
